title: Jackson Bader # your name (or website title) here
logo: "/images/headshot.jpg?raw=true" height="auto" width="200" style="border-radius:50%" # your photo (or logo) here<img src="YOUR_IMAGE_URL" height="auto" width="200" style="border-radius:50%">

description: > # your text below (remove <br> elements if you don't need line breaks)
  I am an aerospace engineering graduate from San Diego State University with experience in CAD modeling, 
  structural analysis, and systems-level engineering projects. This repository showcases selected technical
  projects and supporting materials.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/jackson-bader">View my LinkedIn profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
